import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/Navbar";
import BreadcrumbBanner from "@/components/BreadCrumbBanner";
import VisaCategoriesSection from "@/components/VisaCategoriesSection";
import HomeBanner from "@/components/HomeBanner";
import ExpertGuidanceSection from "@/components/ExpertGuidanceSection";
import WhyChoose from "@/components/WhyChoose";
import Timeline from "@/components/Timeline";
import Footer from "@/components/ui/Footer";



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Navbar/>
     <HomeBanner/>
     {/* <BreadcrumbBanner/> */}
     <VisaCategoriesSection/>
     <ExpertGuidanceSection/>
     <WhyChoose/>
     {/* <Timeline/> */}
     <Footer/>
    </>
  );
}
