import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/Navbar";
import VisaCategoriesSection from "@/components/VisaCategoriesSection";
import HomeBanner from "@/components/HomeBanner";
import ExpertGuidanceSection from "@/components/ExpertGuidanceSection";
import Timeline from "@/components/Timeline";
import Footer from "@/components/ui/Footer";
import Review from "@/components/Review";
import CountryGrid from "@/components/CountryGrid";
import PartnerBanks from "@/components/PartnerBanks";
import WhyChooseSection from "@/components/WhyChoose";

export default function Home() {
  const whyItems = [
    {
      icon: "/images/icons/chat.png",
      title: "Global Education",
      desc: "From course selection to visa approval, Vidhyaa Route guides your study abroad journey completely.",
    },
    {
      icon: "/images/icons/globe.png",
      title: "Worldwide Insight",
      desc: "We guide admissions to top countries like the UK, USA, Canada, and more.",
    },
    {
      icon: "/images/icons/hands.png",
      title: "Personal Mentorship",
      desc: "Vidhyaa Route offers personalized guidance based on goals, academics, and finances.",
    },
    {
      icon: "/images/icons/money.png",
      title: "Loan Guidance",
      desc: "We assist students in securing personalized education loans through trusted banks and financial institutions.",
    },
  ];
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <HomeBanner />
      {/* <BreadcrumbBanner/> */}
      <VisaCategoriesSection />
      <ExpertGuidanceSection />
      <WhyChooseSection
        label="WHY CHOOSE US"
        title="Vidhyaa Route is your trusted partner, guiding you from admission to arrival abroad."
        items={whyItems}
      />
      <Timeline />
      <Review />
      <CountryGrid />
      <PartnerBanks />
      <Footer />
    </>
  );
}
